name: Release Binaries

on:
  release:
    types:
      - published

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable 

      - name: Build binary
        working-directory: ./distrohoop
        run: cargo build --release

      - name: Verify binary
        run: ls -la ./distrohoop/target/release/

      - name: Upload Linux binary
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./distrohoop/target/release/distrohoop
          asset_name: distrohoop-linux-x64
          asset_content_type: application/octet-stream
          token: ${{ secrets.GH_TOKEN }}

  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Build binary
        working-directory: ./distrohoop
        run: cargo build --release

      - name: Verify binary
        run: dir ./distrohoop/target/release/

      - name: Upload Windows binary
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./distrohoop/target/release/distrohoop.exe
          asset_name: distrohoop-windows-x64.exe
          asset_content_type: application/octet-stream
          token: ${{ secrets.GH_TOKEN }}

  build-macos:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Build binary
        working-directory: ./distrohoop
        run: cargo build --release

      - name: Verify binary
        run: ls -la ./distrohoop/target/release/

      - name: Upload macOS binary
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./distrohoop/target/release/distrohoop
          asset_name: distrohoop-macos-x64
          asset_content_type: application/octet-stream
          token: ${{ secrets.GH_TOKEN }}
